---
version: '2'
services:
  # timeseries database
  influx:
    image: influxdb:1.8-alpine
    volumes:
      - influx_data:/var/lib/influxdb
    hostname: influx-1
    container_name: influx

  # proxy for influx that we can use to flush writes to influx on a fixed interval
  influx-proxy:
    image: chengshiwen/influx-proxy:latest
    hostname: influx
    container_name: influx-proxy
    ports:
      - 8086:8086
    environment:
      - TZ=America/New_York
    volumes:
      - ./influx-proxy.json:/etc/influx-proxy/proxy.json

  # visualizer for the influx data
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - influx-proxy
      - influx


volumes:
  influx_data:
    driver: local